import type { NextPage } from "next";
import Head from "next/head";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Midas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="flex flex-col h-full justify-center items-center">
        <h1 className="xl:text-9xl font-cursive text-yellow-300">
          Golden Touch
        </h1>
        <h1 className="xl:text-9xl font-cursive">Design System</h1>
      </section>
    </>
  );
};

export default Home;
