import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "../components";
import { ComponentWrapper } from "../wrappers/ComponentWrapper";
import { PageWrapper } from "../wrappers/PageWrapper";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>DevHaven</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ComponentWrapper description="Primary Button">
        <Button>Primary stuf</Button>
      </ComponentWrapper>
      <ComponentWrapper description="Disabled Button">
        <Button> Disabled </Button>
      </ComponentWrapper>
    </>
  );
};

export default Home;
