import type { NextPage } from "next";
import Head from "next/head";
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>DevHaven</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <h1 className="xl:text-9xl font-cursive">Design System</h1>
      </section>
    </>
  );
};

export default Home;
